### ISSUE TITLE
v3 - no importer registered for protocol sqlserver

### ISSUE THREAD

**Issue by sqldiablo** [shopmonkeyus/eds-server#159]
v3 issue, trying to run the import function to load to SQL Server, and getting this error:

error creating importer: no importer registered for protocol sqlserver. the following are supported: snowflake, postgres, eventhub, file, kafka, mysql, s3

It looks like this version is missing a driver for SQL Server. The README references SQL Server as a supported target, but I don't see it in the drivers folder in this repo.

**Comment by jhaynie** [comment]
We jumped in the gun a bit on the README but the SQL Server driver is still in [PR Review](https://github.com/shopmonkeyus/eds-server/pull/141). Good news is we're ready to merge and should have it merged tomorrow and another release build then.

**Comment by jhaynie** [comment]
Released in https://github.com/shopmonkeyus/eds-server/releases/tag/v3.1.6
